import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@i18n/routing";
import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import Header from "@components/header";
import { ApolloWrapper } from "@lib/apolloWrapper";
import "./globals.css";

const orbitronSans = Orbitron({
  variable: "--font-orbitron-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={`${orbitronSans.variable} antialiased`}>
        <NextIntlClientProvider>
          <ApolloWrapper>
            <Header />
            {children}
          </ApolloWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
